Update and migrate routes, eliminate vulnerabilities
FractalHQ/sveltekit-electron pull request #28
Opened 2022-09-28 10:23 UTC by sc00

Migration after latest SvelteKit API changes, packages updated, vulnerabilities eliminated with overrides, README updated

2022-09-28 15:08 UTC, ghostdevv requested changes

2022-09-28 15:08 UTC, ghostdevv commented on package.json
> +			"got": "12.1.0"
```suggestion
			"got": "^12.5.1"
```

2022-09-28 15:21 UTC, ghostdevv requested changes

2022-10-02 02:06 UTC, ghostdevv approved these changes
LGTM

2022-10-02 02:25 UTC, FractalHQ approved these changes

2022-10-02 02:38 UTC, merged